### ISSUE TITLE
timeline—could zoom on change of active narrative node

### ISSUE THREAD

**Issue by phelow** [pcioni/CISL#18] opened 2016-10-12 15:04 UTC
this  change would happen when traversing the narrative—play button on timeline screen, and journal next / previous node buttons, as well as when you select a node at a user turn / interactive decision point (because it creates new node connections).

**Comment by ludimation** [comment] 2016-12-01 22:24
Dupe of #68

**Closed by ludimation** 2016-12-01 22:24 UTC
Labels: feature request
